// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU_wT5ZciQLRPjqBQFDxJxwJob9kJq60w',
    appId: '1:216168634193:web:d5cc0fba82ef0456a22570',
    messagingSenderId: '216168634193',
    projectId: 'createsocialmmb',
    authDomain: 'createsocialmmb.firebaseapp.com',
    storageBucket: 'createsocialmmb.appspot.com',
    measurementId: 'G-PM7YTWZFTK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA41s0CkyrneVcuEw9RElmGFKkONdUaRDg',
    appId: '1:216168634193:android:3ddce925ad55ab1da22570',
    messagingSenderId: '216168634193',
    projectId: 'createsocialmmb',
    storageBucket: 'createsocialmmb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyuG5FiGbEannvG4si8JnFjR3xX_IpOVU',
    appId: '1:216168634193:ios:e11367405a54a8f6a22570',
    messagingSenderId: '216168634193',
    projectId: 'createsocialmmb',
    storageBucket: 'createsocialmmb.appspot.com',
    iosClientId: '216168634193-ofiigjr2bdnptn4e41bkp63eodc1pfkn.apps.googleusercontent.com',
    iosBundleId: 'com.creationdriven.createSocial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyuG5FiGbEannvG4si8JnFjR3xX_IpOVU',
    appId: '1:216168634193:ios:873c39ed8afb42c4a22570',
    messagingSenderId: '216168634193',
    projectId: 'createsocialmmb',
    storageBucket: 'createsocialmmb.appspot.com',
    iosClientId: '216168634193-gp26circpsf8vm06rc93i14k4f7f5vqe.apps.googleusercontent.com',
    iosBundleId: 'com.example.createsocial',
  );
}
